from __future__ import annotations

DEFAULT_IMPLEMENTER_MODEL = "gpt-5.4 high"
DEFAULT_REVIEWER_MODEL = "gpt-5.4 medium"
DEFAULT_ORACLE_MODEL = "gpt-5.4-mini low"
IMPLEMENTER_APPROVALS_REVIEWER = "auto_review"
IMPLEMENTER_APPROVAL_POLICY = "on-request"
MAX_REVIEWER_TOOL_RETRIES = 2
REASONING_EFFORTS = {"none", "minimal", "low", "medium", "high", "xhigh"}
APP_SERVER_COMPACTION_TIMEOUT_SECONDS = 900
APP_SERVER_TOKEN_USAGE_TIMEOUT_SECONDS = 30
APP_SERVER_ORACLE_TURN_TIMEOUT_SECONDS = 300
APP_SERVER_ROLLBACK_TIMEOUT_SECONDS = 60
CODEX_TUI_CONTEXT_BASELINE_TOKENS = 12_000
ORACLE_STATUSES = {
    "ONLY_REJECTED_FINDINGS",
    "HAS_REJECTED_AND_NEW_FINDINGS",
    "NO_REJECTED_FINDINGS",
}
NO_FINDINGS = "NO_FINDINGS"
